# openapi_v5_ultimate.yaml
openapi: 3.1.0
info:
  title: ncOS v5 Ultimate Trading API
  version: 5.0.0
  description: Unified trading intelligence with interactive pair selection

servers:
  - url: https://emerging-tiger-fair.ngrok-free.app
    description: ncOS v5 Server

paths:
  /api/menu:
    get:
      summary: Get interactive menu
      operationId: getMenu
      responses:
        '200':
          description: Menu options
          content:
            application/json:
              schema:
                type: object
                
  /api/action:
    post:
      summary: Execute menu action
      operationId: executeAction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                  enum: [select_pair, load_data, analyze, score_setup, generate_chart]
                params:
                  type: object
      responses:
        '200':
          description: Action result
          
  /api/quick_analysis/{pair}:
    get:
      summary: Quick analysis for trading pair
      operationId: quickAnalysis
      parameters:
        - name: pair
          in: path
          required: true
          schema:
            type: string
            enum: [XAUUSD, EURUSD, GBPUSD, BTCUSD, ETHUSD, US30, GBPJPY]
      responses:
        '200':
          description: Analysis and score